### ISSUE TITLE
Cubic debian stuck at 50%

### ISSUE THREAD

**Issue by tiberyunt** [PJ-Singh-001/Cubic#221]
I tried to make a custom debian image (Debian 11) and it is stuck at 50%.
Here is the log from the terminal:

Exception in thread Thread-10 (navigate):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/cubic/cubic/navigator.py", line 613, in navigate
    result = new_page.enter(action, page) if new_page else None
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/pages/generate_page.py", line 144, in enter
    is_error = copy_kernel_files()
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/pages/generate_page.py", line 377, in copy_kernel_files
    is_pop_os_based = constructor.os_is_distribution('pop', model.project.custom_root_directory)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/utilities/constructor.py", line 245, in os_is_distribution
    key, value = line.split('=', 1)
    ^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by PJ-Singh-001** [comment]
What version of Cubic is this?

**Comment by KotlVeridian** [comment]
It is version '2023.05-83-release~202305230205~ubuntu22.04.1', I used it on Debian 12 pre-release and ubuntu 22.10 (Vanilla OS with abroot).

**Comment by KotlVeridian** [comment]
> What version of Cubic is this?

It is version '2023.05-83-release202305230205ubuntu22.04.1', I used it on Debian 12 pre-release and ubuntu 22.10 (Vanilla OS with abroot).

**Comment by tiberyunt** [comment]
> What version of Cubic is this?

It is version '2023.05-83-release202305230205ubuntu22.04.1', I used it on Debian 12 pre-release and ubuntu 22.10 (Vanilla OS with abroot).

**Comment by PJ-Singh-001** [comment]
@KotlVeridian,

Did you mean to close this issue?
