### ISSUE TITLE
Project fails to build when host machine has changed its kernel

### ISSUE THREAD

**Issue by asamimichan** [PJ-Singh-001/Cubic#327]
I have a project that I started with my host machine (the pc I have cubic installed on) running debian kernel 6.0.21
A few days ago I updated my machine and now it's on kernel 6.0.22

When I launch cubic, the project fails to build, shows no kernels in the kernel dialog, no compression, no grub settings, none of it. Nothing works past the console editing phase.

The only workaround  is to reboot my machine, and boot with the kernel 6.0.21. 

I tried to see if in cubic.conf there was something somewhere hardcoded that referenced the kernel i started the project with and change it for my current one but didn't really see anything. 

I have no problem toggling back to 21 just now, but in the future I want to remove 21 and use only the most recent kernels. How can I get my project to work with any kernel of my host machine? <

Error when moving to the boot tab or pressing next to start building the project into the iso:

```
  • The thread id is....................... 140206904702656                     
Exception in thread Thread-6 (navigate):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/cubic/cubic/navigator.py", line 572, in navigate
    result = page.leave(action, new_page) if page else None
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/pages/options_page.py", line 273, in leave
    model.options.boot_configurations = boot_tab.get_required_file_paths()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/utilities/files_tab.py", line 1177, in get_required_file_paths
    return self.files_tree.get_required_file_paths()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_required_file_paths'
```

If I reboot and boot my machine with the kernel i started this project as, the project works. 

Thanks!

**Comment by PJ-Singh-001** [comment]
From Cubic's [Terminal page](https://github.com/PJ-Singh-001/Cubic/wiki/Terminal-Page), what is the output of...

    ls -la /boot

Also, would you please cut and paste your log from the following section, until you experience this error?
> Navigate from terminal page to prepare page on next action

**Comment by asamimichan** [comment]
```
You have entered the virtual environment.
root@cubic:~# ls -la /boot
total 94856
drwxr-xr-x  2 root root     4096 May 12 23:50 .
drwxr-xr-x 17 root root     4096 Feb 10 08:07 ..
-rw-r--r--  1 root root       83 Feb  1 05:05 System.map-6.1.0-18-amd64
-rw-r--r--  1 root root   259453 Feb  1 05:05 config-6.1.0-18-amd64
-rw-r--r--  1 root root 88702163 May 12 23:50 initrd.img-6.1.0-18-amd64
-rw-r--r--  1 root root  8152768 Feb  1 05:05 vmlinuz-6.1.0-18-amd64
root@cubic:~# 
```
Console:

```
 • Mouse button 3 pressed for............. terminal page                       
  • Clicked................................ Next                                

Handle navigation from terminal page on next action                             

  • Interrupt previous thread.............. No thread                           

Get the new page                                                                

  • Current page........................... terminal page                       
  • Action................................. next                                
  • New page............................... prepare page                        

Navigate from terminal page to prepare page on next action                      


  Exit virtual environment                 

  • Execute synchronously.................. stop-process 44548                  
  • The thread id is....................... 140140839679680                     
  • The process id is...................... 44600                               

  Exited virtual environment               

  • Process id............................. 44548                               
  • Pseudo terminal........................ 20                                  
  • Status................................. 9                        
  • Signal................................. 9                        
  • Exit Code.............................. 0                        
  • Virtual environment status message..... You are not in the virtual          
                                            environment.                        
  • Cannot unsubscribe from virtual     
    environment entered signals............ The subscription does not exist     
  • MAX_ATTEMPTS........................... 3                                   
  • First time............................. False                               
  • Reenter................................ False                               
  • Attempts............................... 1 of 3 times             
 You have exited the    al................. 
                                            virtual environment.            
  • Delete file............................ /home/asamimi/debian-build/.#custom- 
                                            root.lck                            
  • Execute synchronously.................. delete-path /home/asamimi/debian-    
                                            build/.#custom-root.lck             
  • The process id is...................... 44609                               
  • Attempt to restart the virtual      
    environment?........................... No                                  
  • The result is.......................... None                                
  • The exit status, signal status is...... 0, None                             
  • Show the Packages page?................ No                                  

  Transition pages                         

  • Hide old page.......................... terminal page                       
  • Show new page.......................... prepare page                        

  Create kernel details list               


  Create vmlinuz details list              

  • ▹ Search directory..................... /home/asamimi/debian-build/custom-   
                                            root/boot                           
  • ▹ Number of vmlinuz files found........ 1                                   
  • Get vmlinuz version name from file  
    name................................... /home/asamimi/debian-build/custom-   
                                            root/boot/vmlinuz-6.1.0-18-amd64    
  • ▹ The version name is.................. 6.1.0-18                            
  • ▹ The vmlinuz version is............... 6.1.0-18                            

  Create vmlinuz details list              

  • ▹ Search directory..................... /home/asamimi/debian-build/source-   
                                            disk/live                           
  • ▹ Number of vmlinuz files found........ 2                                   
  • Get vmlinuz version name from file  
    name................................... /home/asamimi/debian-build/source-   
                                            disk/live/vmlinuz                   
  • ▹ The version name is.................. None                                
  • Get vmlinuz version name from file  
    type................................... /home/asamimi/debian-build/source-   
                                            disk/live/vmlinuz                   
  • Execute synchronously.................. file "vmlinuz"                      
  • The process id is...................... 44642                               
  • ▹ The version name is.................. 6.1.0-18                            
  • ▹ The vmlinuz version is............... 6.1.0-18                            
  • Get vmlinuz version name from file  
    name................................... /home/asamimi/debian-build/source-   
                                            disk/live/vmlinuz-6.1.0-18-amd64    
  • ▹ The version name is.................. 6.1.0-18                            
  • ▹ The vmlinuz version is............... 6.1.0-18                            

  Create initrd details list               

  • ▹ Search directory..................... /home/asamimi/debian-build/custom-   
                                            root/boot                           
  • ▹ Number of initrd files found......... 1                                   
  • Get initrd version name from file   
    name................................... /home/asamimi/debian-build/custom-   
                                            root/boot/initrd.img-6.1.0-18-amd64 
  • ▹ The version name is.................. 6.1.0-18                            
  • ▹ The initrd version is................ 6.1.0-18                            
  • Get initrd compression format from  
    file type.............................. /home/asamimi/debian-build/custom-   
                                            root/boot/initrd.img-6.1.0-18-amd64 
  • Execute synchronously.................. file "/home/asamimi/debian-          
                                            build/custom-                       
                                            root/boot/initrd.img-6.1.0-18-amd64"
  • The process id is...................... 44643                               
  • The initrd file type information is.... /home/asamimi/debian-build/custom-   
                                            root/boot/initrd.img-6.1.0-18-amd64:
                                            ASCII cpio archive (SVR4 with no    
                                            CRC)                                
  • Initrd compression format found?....... No                                  
  • Get initrd compression format from  
    file contents.......................... /home/asamimi/debian-build/custom-   
                                            root/boot/initrd.img-6.1.0-18-amd64 
  • Execute asynchronously................. binwalk --include="compressed data" 
                                            "/home/asamimi/debian-build/custom-  
                                            root/boot/initrd.img-6.1.0-18-amd64"
  • The process id is...................... 44644                               
  • The initrd file contents information
    is..................................... 23881544      0x16C6748       gzip  
                                            compressed data, from NTFS          
                                            filesystem (NT), last modified:     
                                            1970-01-01 00:00:00 (null date)     
  • Initrd compression format found?....... Yes                                 
  • The compression format is.............. gzip                                

  Create initrd details list               

  • ▹ Search directory..................... /home/asamimi/debian-build/source-   
                                            disk/live                           
  • ▹ Number of initrd files found......... 2                                   
  • Get initrd version name from file   
    name................................... /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img                
  • ▹ The version name is.................. None                                
  • Get initrd version name from file   
    contents............................... /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img                
  • Execute asynchronously................. lsinitramfs "/home/asamimi/debian-   
                                            build/source-disk/live/initrd.img"  
  • The process id is...................... 44645                               
  • ▹ The version name is.................. 6.1.0-18                            
  • ▹ The initrd version is................ 6.1.0-18                            
  • Get initrd compression format from  
    file type.............................. /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img                
  • Execute synchronously.................. file "/home/asamimi/debian-          
                                            build/source-disk/live/initrd.img"  
  • The process id is...................... 44840                               
  • The initrd file type information is.... /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img: ASCII cpio    
                                            archive (SVR4 with no CRC)          
  • Initrd compression format found?....... No                                  
  • Get initrd compression format from  
    file contents.......................... /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img                
  • Execute asynchronously................. binwalk --include="compressed data" 
                                            "/home/asamimi/debian-build/source-  
                                            disk/live/initrd.img"               
  • The process id is...................... 44841                               
  • The initrd file contents information
    is..................................... 23881371      0x16C669B       gzip  
                                            compressed data, from NTFS          
                                            filesystem (NT), last modified:     
                                            1970-01-01 00:00:00 (null date)     
  • Initrd compression format found?....... Yes                                 
  • The compression format is.............. gzip                                
  • Get initrd version name from file   
    name................................... /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img-6.1.0-18-amd64 
  • ▹ The version name is.................. 6.1.0-18                            
  • ▹ The initrd version is................ 6.1.0-18                            
  • Get initrd compression format from  
    file type.............................. /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img-6.1.0-18-amd64 
  • Execute synchronously.................. file "/home/asamimi/debian-          
                                            build/source-                       
                                            disk/live/initrd.img-6.1.0-18-amd64"
  • The process id is...................... 44842                               
  • The initrd file type information is.... /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img-6.1.0-18-amd64:
                                            ASCII cpio archive (SVR4 with no    
                                            CRC)                                
  • Initrd compression format found?....... No                                  
  • Get initrd compression format from  
    file contents.......................... /home/asamimi/debian-build/source-   
                                            disk/live/initrd.img-6.1.0-18-amd64 
  • Execute asynchronously................. binwalk --include="compressed data" 
                                            "/home/asamimi/debian-build/source-  
                                            disk/live/initrd.img-6.1.0-18-amd64"
  • The process id is...................... 44843                               
  • The initrd file contents information
    is..................................... 23881371      0x16C669B       gzip  
                                            compressed data, from NTFS          
                                            filesystem (NT), last modified:     
                                            1970-01-01 00:00:00 (null date)     
  • Initrd compression format found?....... Yes                                 
  • The compression format is.............. gzip                                
  • Delete existing files with pattern..... /var/tmp/unmkinitramfs_*            
  • Delete file............................ /var/tmp/unmkinitramfs_b9pOOx       
  • Execute synchronously.................. delete-path                         
                                            /var/tmp/unmkinitramfs_b9pOOx       
  • The process id is...................... 44844                               
  • The result is.......................... None                                
  • The exit status, signal status is...... 0, None                             

  Collate kernel versions                  

  • Directory.............................. /home/asamimi/debian-build/custom-   
                                            root/boot                           
  • Matching vmlinuz and initrd versions... 6.1.0-18                            
  • Directory.............................. /home/asamimi/debian-build/source-   
                                            disk/live                           
  • Matching vmlinuz and initrd versions... 6.1.0-18                            
  • Directory.............................. /home/asamimi/debian-build/source-   
                                            disk/live                           
  • Matching vmlinuz and initrd versions... 6.1.0-18                            
  • Directory.............................. /home/asamimi/debian-build/source-   
                                            disk/live                           
  • Matching vmlinuz and initrd versions... 6.1.0-18                            
  • Directory.............................. /home/asamimi/debian-build/source-   
                                            disk/live                           
  • Matching vmlinuz and initrd versions... 6.1.0-18                            

  List the kernel details                  

  • Version................................ 6.1.0-18                            
  • ▹ Index................................ 1 of 5                              
  • ▹ Vmlinuz file name.................... vmlinuz-6.1.0-18-amd64              
  • ▹ New vmlinuz file name................ vmlinuz                             
  • ▹ Initrd file name..................... initrd.img-6.1.0-18-amd64           
  • ▹ New initrd file name................. initrd.gz                           
  • ▹ Directory............................ /home/asamimi/debian-build/source-   
                                            disk/live                           
  • ▹ Note................................. This kernel is used to bootstrap the
                                            original disk. Select this kernel if
                                            you are unable to boot the disk     
                                            using other kernel versions.        
                                            Reference these files as <span font_
                                            family="monospace">vmlinuz</span>   
                                            and <span font_family="monospace">in
                                            itrd.gz</span> in the disk boot     
                                            configurations.                     
  • ▹ Is selected.......................... True                                
  • Version................................ 6.1.0-18                            
  • ▹ Index................................ 2 of 5                              
  • ▹ Vmlinuz file name.................... vmlinuz-6.1.0-18-amd64              
  • ▹ New vmlinuz file name................ vmlinuz                             
  • ▹ Initrd file name..................... initrd.img-6.1.0-18-amd64           
  • ▹ New initrd file name................. initrd.gz                           
  • ▹ Directory............................ /home/asamimi/debian-build/custom-   
                                            root/boot                           
  • ▹ Note................................. This kernel is installed in the     
                                            <span                               
                                            font_family="monospace">/boot</span>
                                            directory of the Linux file system  
                                            and can be used to bootstrap the    
                                            customized disk. Reference these    
                                            files as <span font_family="monospac
                                            e">vmlinuz</span> and <span font_fam
                                            ily="monospace">initrd.gz</span> in 
                                            the disk boot configurations.       
  • ▹ Is selected.......................... False                               
  • Version................................ 6.1.0-18                            
  • ▹ Index................................ 3 of 5                              
  • ▹ Vmlinuz file name.................... vmlinuz-6.1.0-18-amd64              
  • ▹ New vmlinuz file name................ vmlinuz                             
  • ▹ Initrd file name..................... initrd.img                          
  • ▹ New initrd file name................. initrd.gz                           
  • ▹ Directory............................ /home/asamimi/debian-build/source-   
                                            disk/live                           
  • ▹ Note................................. This kernel is used to bootstrap the
                                            original disk. Select this kernel if
                                            you are unable to boot the disk     
                                            using other kernel versions.        
                                            Reference these files as <span font_
                                            family="monospace">vmlinuz</span>   
                                            and <span font_family="monospace">in
                                            itrd.gz</span> in the disk boot     
                                            configurations.                     
  • ▹ Is selected.......................... False                               
  • Version................................ 6.1.0-18                            
  • ▹ Index................................ 4 of 5                              
  • ▹ Vmlinuz file name.................... vmlinuz                             
  • ▹ New vmlinuz file name................ vmlinuz                             
  • ▹ Initrd file name..................... initrd.img-6.1.0-18-amd64           
  • ▹ New initrd file name................. initrd.gz                           
  • ▹ Directory............................ /home/asamimi/debian-build/source-   
                                            disk/live                           
  • ▹ Note................................. This kernel is used to bootstrap the
                                            original disk. Select this kernel if
                                            you are unable to boot the disk     
                                            using other kernel versions.        
                                            Reference these files as <span font_
                                            family="monospace">vmlinuz</span>   
                                            and <span font_family="monospace">in
                                            itrd.gz</span> in the disk boot     
                                            configurations.                     
  • ▹ Is selected.......................... False                               
  • Version................................ 6.1.0-18                            
  • ▹ Index................................ 5 of 5                              
  • ▹ Vmlinuz file name.................... vmlinuz                             
  • ▹ New vmlinuz file name................ vmlinuz                             
  • ▹ Initrd file name..................... initrd.img                          
  • ▹ New initrd file name................. initrd.gz                           
  • ▹ Directory............................ /home/asamimi/debian-build/source-   
                                            disk/live                           
  • ▹ Note................................. This kernel is used to bootstrap the
                                            original disk. Select this kernel if
                                            you are unable to boot the disk     
                                            using other kernel versions.        
                                            Reference these files as <span font_
                                            family="monospace">vmlinuz</span>   
                                            and <span font_family="monospace">in
                                            itrd.gz</span> in the disk boot     
                                            configurations.                     
  • ▹ Is selected.......................... False                               
  • Number of valid disk boot kernels   
    found.................................. 5                                   

  Create list of installed packages        

  • Execute synchronously.................. dpkg-query                          
                                            --admindir="/home/asamimi/debian-    
                                            build/custom-root/var/lib/dpkg"     
                                            --show                              
  • The process id is...................... 44851                               
  • Number of installed packages found..... 3051                                

  Create the removable packages list for a 
  typical install                          

  • Read lines from file................... /home/asamimi/debian-build/custom-   
                                            disk/live/filesystem.manifest-remove
  • Warning. File does not exist........... /home/asamimi/debian-build/custom-   
                                            disk/live/filesystem.manifest-remove
  • Total number of installed packages..... 3051                                
  • Number of packages to be removed for
    a typical install...................... 0                                   
  • Number of packages to be retained   
    for a typical install.................. 3051                                
  • Number of installed packages        
    matching typical install list.......... 0                                   

  Create the removable packages list for a 
  minimal install                          

  • Read lines from file................... /home/asamimi/debian-build/custom-   
                                            disk/live/filesystem.manifest-      
                                            minimal-remove                      
  • Warning. File does not exist........... /home/asamimi/debian-build/custom-   
                                            disk/live/filesystem.manifest-      
                                            minimal-remove                      
  • Total number of installed packages..... 3051                                
  • Number of packages to be removed for
    a minimal install...................... 0                                   
  • Number of packages to be retained   
    for a minimal install.................. 3051                                
  • Number of installed packages        
    matching minimal install list.......... 0                                   

  Create new file system manifest file     

  • Write file system manifest to.......... /home/asamimi/debian-build/custom-   
                                            disk/live/filesystem.manifest       
  • Show the Packages page?................ No                                  

Get the new page                                                                

  • Current page........................... prepare page                        
  • Action................................. next options                        
  • New page............................... options page                        

Navigate from prepare page to options page on next options action               


  Transition pages                         

  • Hide old page.......................... prepare page                        
  • Show new page.......................... options page                        

  Initialize Kernel Tab                    


  Initialize Preseed Tab                   


  Initialize Files Tab                     

  • Create directory....................... /home/asamimi/debian-build/custom-   
                                            disk/preseed                        
  • Not creating directory................. Directory already exists            

  Initialize files tree                    

  • The root file paths are................ ['preseed']                         
  • The required file paths are............ None                                

  Build tree                               

  • File path.............................. preseed                             
  • Source file path....................... preseed                             
  • Adding watch for....................... /home/asamimi/debian-build/custom-   
                                            disk/preseed                        
  • Asyncio thread......................... Start                               

  Initialize Boot Tab                      


  Initialize Files Tab                     

  • Create all directories in the path..... /home/asamimi/debian-build/custom-   
                                            disk/boot                           
  • Not creating directories............... The directory path already exists   

  Initialize files tree                    

  • The root file paths are................ ['boot', 'isolinux']                
  • The required file paths are............ ['boot/grub/grub.cfg',              
                                            'boot/grub/install.cfg',            
                                            'boot/grub/install_start.cfg',      
                                            'isolinux/live.cfg',                
                                            'isolinux/splash.png',              
                                            'isolinux/splash800x600.png']       
Traceback (most recent call last):
  File "/usr/share/cubic/cubic/pages/options_page.py", line 510, in setup_boot_tab
    boot_tab.create_tree(root_file_paths, model.options.boot_configurations)
  File "/usr/share/cubic/cubic/utilities/files_tab.py", line 145, in create_tree
    self.files_tree = FilesTree(root_file_paths=root_file_paths, selection_changed=self.show_pane_for_file, required_file_paths=required_file_paths)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/cubic/cubic/utilities/files_tree.py", line 247, in __init__
    self.watch_manager = pyinotify.WatchManager()
                         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyinotify.py", line 1764, in __init__
    raise OSError(err % self._inotify_wrapper.str_errno())
OSError: Cannot initialize new instance of inotify, Errno=Too many open files (EMFILE)

  Show Options page, Kernel tab            

  • Change tree selection to............... preseed                             
  • Show pane for file..................... preseed                             
  • Change tree selection to............... preseed                             
  • Show pane for file..................... preseed      
```

**Comment by PJ-Singh-001** [comment]
Thanks.

On your host machine, what is the output of...

    cat /proc/sys/fs/inotify/max_user_instances

Am I correct in assuming you updated these two files?...

    isolinux/splash.png
    isolinux/splash800x600.png

Did you modify or change other files in `/home/asamimi/debian-build/custom-disk/boot`?

(If you did, that's perfectly fine, and Cubic should support you doing that, but knowing this may help in debugging this issue).
