### ISSUE TITLE
Install error from custom image

### ISSUE THREAD

**Issue by asilnov** [PJ-Singh-001/Cubic#345]
**Describe the question**

During creation custom image of Ubuntu 20.04 in virtual env terminal I upgraded packages and installed net-tools. 
After creation I tried to install the image on my baremetal server and got the installation error:
```
         Running command ['udevadm', 'settle'] with allowed return codes [0] (capture=False)
         TIMED udevadm_settle(): 0.024
         Detected multipath support, reload maps
         Running command ['multipath', '-r'] with allowed return codes [0] (capture=False)
         Sep 06 21:49:10 | DM multipath kernel driver not loaded
         finish: cmd-install/stage-partitioning/builtin/cmd-block-meta/clear-holders: FAIL: removing previous storage devices
         TIMED BLOCK_META: 1.470
         finish: cmd-install/stage-partitioning/builtin/cmd-block-meta: FAIL: curtin command block-meta
         Traceback (most recent call last):
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/commands/main.py", line 202, in main
             ret = args.func(args)
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/log.py", line 97, in wrapper
             return log_time("TIMED %s: " % msg, func, *args, **kwargs)
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/log.py", line 79, in log_time
             return func(*args, **kwargs)
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/commands/block_meta.py", line 108, in block_meta
             meta_clear(devices, state.get('report_stack_prefix', ''))
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/commands/block_meta.py", line 1983, in meta_clear
             clear_holders.start_clear_holders_deps()
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/block/clear_holders.py", line 691, in start_clear_holders_deps
             multipath.reload()
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/block/multipath.py", line 229, in reload
             util.subp(['multipath', '-r'])
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/util.py", line 275, in subp
             return _subp(*args, **kwargs)
           File "/snap/subiquity/3698/lib/python3.8/site-packages/curtin/util.py", line 139, in _subp
             raise ProcessExecutionError(stdout=out, stderr=err,
         curtin.util.ProcessExecutionError: Unexpected error while running command.
         Command: ['multipath', '-r']
         Exit code: 1
         Reason: -
         Stdout: ''
         Stderr: ''
         Unexpected error while running command.
         Command: ['multipath', '-r']
         Exit code: 1
         Reason: -
         Stdout: ''
         Stderr: ''
```

**OS Information (please complete the following information):**
 - OS/Distro Name: Ubuntu
 - OS Version Ubuntu 20.04.6 LTS

**Cubic Information (please complete the following information):**
 - Cubic Version: 2024.09-89-release\~202409062212\~ubuntu20.04.1
 - ISO Customizing: ubuntu-20.04.6-live-server-amd64.iso
 - Download Link:  [ubuntu-20.04.6-live-server-amd64.iso](https://releases.ubuntu.com/focal/ubuntu-20.04.6-live-server-amd64.iso)

**Comment by PJ-Singh-001** [comment]
I can see the issue seems to have something to do with partitioning.

    cmd-install/stage-partitioning/builtin/cmd-block-meta/clear-holders: FAIL: removing previous storage devices

Could be that you've updated something that the installer is not happy about.

With Subiquity, Canonical introduced ISOs with a layered file system.
The 20.04 Server ISO has only two layers:
 1. The "Standard" Linux file system
    - This is what you can customize in Cubic
    - This is what gets installed onto your computer
 2. The "Installer" Linux file system
    - This contains Subiquity and additional files, packages, and snaps needed in the Live Environment
    - Cubic can not customize this, for technical reasons I have not been able to overcome
    - This file system does NOT get installed onto your computer

I suspect what might be happening is, some of the files on the "Installer" (2) file system need specific files on the "Standard" (1) file system. But you've upgraded the files on the "Standard" (1) file system.

I think you may be able to build a custom install if you selectively update packages.

Based on your error log, I suspect the package `udev` (which contains the command `udevadm`) can not be upgraded.

> `Running command ['udevadm', 'settle'] with allowed return codes [0] (capture=False)`

Perhaps you could try selectively upgrading packages, excluding ones that the "Installer" (2) file system needs specific versions of. 

I agree this is not an easy task. As an initial step, try keeping `udev` unchanged, as I suggested.

Unfortunately, the introduction of Subiquity and Snaps has really impacted our ability to customize the ISO. (With the latest version of Cubic, I was able to combine the "Minimal" and "Standard" files systems, which appear on the Desktop ISO, but the "Installer" file system for both Desktop and Server ISOs is something I have not been able to enable customization of yet).

**Comment by BadKid90s** [comment]
![image](https://github.com/user-attachments/assets/ccebfd09-93cc-4a46-aa07-80d11c64ca49)
![{e3267682-9fae-4811-ab99-50fd6c4b760f}](https://github.com/user-attachments/assets/13ba16d0-2571-460f-ac3f-05b0f4552b34)
![image](https://github.com/user-attachments/assets/88dee076-dff1-407f-bffa-424f1403237b)



ISO：https://releases.ubuntu.com/20.04.6/

I used Cubic to customize the ISO without making any changes, but encountered this issue during installation. Please tell me how to solve this problem？

**Comment by xpy3306** [comment]
I also encountered the same problem, without any operation, just clicking next, and the exported iso also reported the same error

**Comment by kannanvr** [comment]
We are also facing the similar error. @PJ-Singh-001 , pls help here how to  solve it

**Comment by PPPDUD** [comment]
Can confirm this issue is still active on Ubuntu Server 25.04 @PJ-Singh-001
